version: '3.9'

networks:
  network_recipes:
    driver: bridge

services:
  mysql:
    image: mysql:8
    container_name: mysql_recipes
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: recipes
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    networks:
      - network_recipes
